### ISSUE TITLE
btrfs support

### ISSUE THREAD

**Issue by renich** [r1k0/kicktoo#20]
Hello,

I like using btrfs in general. It would be cool if you could provide btrfs support (subvolumes included) for installation.

Thanks

**Comment by r1k0** [comment]
Hello,

btrfs should be usable already depending on the support of the used livecd.
However, note that the partition runstep is currently broken due to to some changes in sfdisk (didn't found time to fix yet). Therefore the partitioning will fail. To overcome this, you can comment the "part" calls in the desired profile and directly use the "format" call with btrfs/bfs. Remember it is the livecd that brings support for filesystem types.

The format call is defined here: https://github.com/r1k0/kicktoo/blob/0cea2f822b4be715218fa69c425b4f5ab77e34cc/modules/runsteps.sh#L236
Note that there is an existing case for btrfs.

If you encounter further issues, do not hesitate to copy/paste your output and the profile used, I'll try to help shade some lights where I can.

Also, note that there are pre_ and post_ functions available in profiles that you could use to alter or skip a runstep. Have a read of pre_/post_ functions in other profiles to see examples. This will allow your profile to customize the format functions or any other functions.

Have a good day
